"""
RemoteEmbeddingFunction
=======================
A ChromaDB-compatible EmbeddingFunction that delegates embedding generation
to the Shared Embedding Service.

Copy this file into any app that needs it, or install the package and import it.

Usage with a local ChromaDB instance
-------------------------------------
    import chromadb
    from client import RemoteEmbeddingFunction

    ef = RemoteEmbeddingFunction(
        api_key="ses-...",
        url="http://localhost:8000",
    )

    client = chromadb.Client()
    collection = client.create_collection("my_docs", embedding_function=ef)

    # Adding documents — embeddings are generated by the remote service
    collection.add(documents=["Hello world", "Foo bar"], ids=["1", "2"])

    # Querying — the query is also embedded via the remote service
    results = collection.query(query_texts=["greetings"], n_results=2)

Usage with the hosted service API (no local ChromaDB needed)
-------------------------------------------------------------
    import requests

    API_KEY = "ses-..."
    BASE    = "http://localhost:8000"
    HEADERS = {"X-API-Key": API_KEY}

    # Add documents
    requests.post(f"{BASE}/collections/my_docs/documents", headers=HEADERS, json={
        "documents": ["Hello world", "Foo bar"],
        "ids": ["1", "2"],
    })

    # Query
    r = requests.post(f"{BASE}/collections/my_docs/query", headers=HEADERS, json={
        "query_texts": ["greetings"],
        "n_results": 2,
    })
    print(r.json())
"""

from __future__ import annotations

from typing import List

import requests

try:
    from chromadb import EmbeddingFunction, Documents, Embeddings

    _BASE_CLASS = EmbeddingFunction
except ImportError:
    # chromadb is not installed in the client environment — fall back to a plain
    # object so the class can still be imported and the __call__ method used.
    _BASE_CLASS = object  # type: ignore[assignment,misc]
    Documents = List[str]  # type: ignore[misc]
    Embeddings = List[List[float]]  # type: ignore[misc]


class RemoteEmbeddingFunction(_BASE_CLASS):
    """
    Drop-in ChromaDB EmbeddingFunction backed by the Shared Embedding Service.

    Parameters
    ----------
    api_key : str
        The ``ses-...`` API key returned when you registered your app.
    url : str
        Base URL of the Shared Embedding Service (default: http://localhost:8000).
    timeout : int
        Request timeout in seconds (default: 30).
    """

    def __init__(
        self,
        api_key: str,
        url: str = "http://localhost:8000",
        timeout: int = 30,
    ) -> None:
        self.url = url.rstrip("/")
        self.timeout = timeout
        self._headers = {
            "X-API-Key": api_key,
            "Content-Type": "application/json",
        }

    def __call__(self, input: Documents) -> Embeddings:  # noqa: A002
        response = requests.post(
            f"{self.url}/embed",
            json={"texts": list(input)},
            headers=self._headers,
            timeout=self.timeout,
        )
        response.raise_for_status()
        return response.json()["embeddings"]
